# Generated by Django 3.2.16 on 2022-11-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='myName',
            field=models.CharField(default='Samak Customer', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
