# Generated by Django 3.2.16 on 2022-11-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20221102_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(default='samakwardak777@gmail.com', max_length=254),
        ),
    ]
