# Generated by Django 3.2.16 on 2022-11-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='email',
        ),
    ]
